import Link from "next/link";

export function Footer() {
  return (
    <footer className="border-t border-white/5 bg-surface-800/50">
      <div className="mx-auto max-w-6xl px-6 py-12">
        <div className="flex flex-col items-start justify-between gap-8 md:flex-row md:items-center">
          <div>
            <div className="flex items-center gap-2.5">
              <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-gradient-to-br from-brand-500 to-brand-700 text-xs font-bold text-white">
                SK
              </div>
              <span className="font-semibold">
                SKU<span className="text-brand-400">Blast</span>
              </span>
            </div>
            <p className="mt-3 max-w-sm text-sm text-gray-500">
              Bulk SKU listing automation for manufacturers and wholesale sellers.
            </p>
          </div>

          <div className="flex flex-col gap-3 text-sm text-gray-400 md:items-end">
            <Link href="/demo" className="transition hover:text-white">
              Interactive Demo
            </Link>
            <Link href="/research" className="transition hover:text-brand-300">
              How we found this idea →
            </Link>
          </div>
        </div>

        <div className="mt-10 flex flex-col items-start justify-between gap-4 border-t border-white/5 pt-8 text-xs text-gray-600 md:flex-row md:items-center">
          <p>Mock demo · Generated by Idea Miner · Not affiliated with Amazon, eBay, or Flipkart</p>
          <p>© {new Date().getFullYear()} SKUBlast</p>
        </div>
      </div>
    </footer>
  );
}
