import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Research — SKUBlast",
  description:
    "How Idea Miner validated SKUBlast: real pain points, validation checklist, and source links.",
};

const checklistItems = [
  { label: "10+ posts with this pain", passed: true },
  { label: "Paying for inferior solution", passed: true },
  { label: "Reachable channel", passed: true },
  { label: "MVP < 4 weeks", passed: true },
  { label: "Price point high enough", passed: true },
  { label: "Hair-on-fire problem", passed: true },
  { label: "Can pre-sell", passed: true },
  { label: "< 3 competitors", passed: true },
  { label: "AI-agent operable", passed: true },
];

const painPoints = [
  {
    problem:
      "Ecommerce store owners spend excessive time on repetitive duties like updating inventory, managing catalogs, processing orders, and correcting listing mistakes.",
    persona: "Ecommerce store owner",
    workaround: "Manual inventory updates, catalog management, order processing",
    frequency: "daily",
    wtp: "Actively seeking AI inventory assistant",
    url: "https://www.reddit.com/r/IndiaBusiness/comments/1u5j41a/need_help_managing_your_ecommerce_store_lets_talk/",
  },
  {
    problem:
      "Uploading thousands of SKUs to ecommerce marketplaces is labor-intensive; manufacturers need to manually organize product sheets and match them to templates.",
    persona: "Ecommerce seller, manufacturer",
    workaround: "Manual SKU organization and template population, hiring listing agencies",
    frequency: "monthly",
    wtp: "Already paying listing agencies per-SKU-per-marketplace",
    url: "https://www.reddit.com/r/IndiaBusiness/comments/1uf9kcv/is_listing_on_the_ecommerce_platform_painful_and/",
  },
  {
    problem:
      "Abandoned cart recovery, customer categorization, order distribution, inventory alerts, and follow-up emails require manual setup and management.",
    persona: "Ecommerce store owner, Shopify user",
    workaround: "Manual setup of automations or repetitive manual tasks",
    frequency: "daily",
    wtp: "Already using Shopify, seeking better automation",
    url: "https://www.reddit.com/r/ecommerce/comments/1uotfct/what_shopify_automation_has_been_the_biggest/",
  },
  {
    problem:
      "Creating product descriptions for ecommerce listings is tedious; manually entering brand, condition, year, and specs for each product.",
    persona: "Ecommerce seller, vintage guitar store",
    workaround: "Manual product description creation",
    frequency: "daily",
    wtp: "Built custom solution using Claude API",
    url: "https://www.reddit.com/r/ecommerce/comments/1uotfct/what_shopify_automation_has_been_the_biggest/",
  },
];

const coreFeatures = [
  "Bulk product sheet ingestion: upload CSV/Excel with raw product specs; AI maps columns to marketplace-specific required fields",
  "AI listing generator: produces SEO-optimized titles, bullet points, and descriptions per marketplace's style guide using self-hosted LLM",
  "Marketplace publisher: direct API push to Amazon Seller Central, eBay, Flipkart, and Shopify",
  "Listing quality scorer: flags incomplete or low-quality listings before publish with suggested fixes",
  "Variant handler: auto-generates parent-child ASIN/listing structures for products with size/color variants",
];

export default function ResearchPage() {
  return (
    <div className="mx-auto max-w-3xl px-6 py-16">
      <div className="mb-12">
        <Link href="/" className="text-sm text-brand-400 transition hover:text-brand-300">
          ← Back to SKUBlast
        </Link>
        <h1 className="mt-4 text-4xl font-bold tracking-tight">Research Story</h1>
        <p className="mt-3 text-lg text-gray-400">
          How Idea Miner found, validated, and built this demo for SKUBlast.
        </p>
      </div>

      <article className="prose-research space-y-12">
        {/* Why this research program exists */}
        <section>
          <h2 className="text-2xl font-bold text-white">Why this research program exists</h2>
          <p className="mt-4 leading-relaxed text-gray-300">
            This app was auto-generated by the <strong className="text-white">Idea Miner</strong> pipeline — a
            twice-daily research program that hunts for validated micro-SaaS opportunities from real people
            expressing real pain online (Reddit, Hacker News, Stack Exchange, GitHub, and more).
          </p>

          <h3 className="mt-8 text-lg font-semibold text-white">What we&apos;re looking for</h3>
          <ul className="mt-4 space-y-3 text-gray-300">
            <li className="flex gap-3">
              <span className="text-brand-400">→</span>
              <span><strong className="text-white">Self-running micro-SaaS</strong> — one specific problem, a small dedicated user base, minimal manual ops (digital-nomad friendly).</span>
            </li>
            <li className="flex gap-3">
              <span className="text-brand-400">→</span>
              <span><strong className="text-white">AI-agent operable</strong> — daily support, content, and processing handled by autonomous agents on self-hosted LLMs (not locked into expensive cloud API token bills).</span>
            </li>
            <li className="flex gap-3">
              <span className="text-brand-400">→</span>
              <span><strong className="text-white">Real pain only</strong> — every idea must trace back to actual posts where people complain, ask &ldquo;is there a tool for X?&rdquo;, or say &ldquo;I wish someone would build…&rdquo;.</span>
            </li>
            <li className="flex gap-3">
              <span className="text-brand-400">→</span>
              <span><strong className="text-white">B2B & recurring revenue preferred</strong> — higher willingness to pay, lower churn.</span>
            </li>
            <li className="flex gap-3">
              <span className="text-brand-400">→</span>
              <span><strong className="text-white">Markets with &lt;3 established competitors</strong> — room for a focused wedge.</span>
            </li>
            <li className="flex gap-3">
              <span className="text-brand-400">→</span>
              <span><strong className="text-white">MVP in under 4 weeks</strong> — solo-dev buildable, no regulatory/hardware/capital barriers.</span>
            </li>
          </ul>
        </section>

        {/* Why this demo was built */}
        <section className="glass-card p-6">
          <h2 className="text-2xl font-bold text-white">Why this demo was built</h2>
          <p className="mt-4 leading-relaxed text-gray-300">
            When an idea passes the validation gate (≥8/9 checklist items, not declining on Google
            Trends, not previously built), the pipeline automatically ships a working mock on
            Vercel so we can see the product story, not just a slide deck.
          </p>
        </section>

        {/* This specific idea */}
        <section>
          <h2 className="text-2xl font-bold text-white">This specific idea</h2>
          <div className="mt-6 grid gap-4 sm:grid-cols-2">
            <div className="glass-card p-5">
              <div className="text-sm text-gray-500">Weighted Score</div>
              <div className="mt-1 text-3xl font-bold text-brand-300">96/130</div>
            </div>
            <div className="glass-card p-5">
              <div className="text-sm text-gray-500">Validation</div>
              <div className="mt-1 text-3xl font-bold text-emerald-400">9/9 ✓</div>
            </div>
          </div>

          <div className="mt-6 space-y-4 text-gray-300">
            <p>
              <strong className="text-white">Cluster:</strong> Ecommerce Bulk SKU Listing Automation
            </p>
            <p>
              <strong className="text-white">Why we built this demo:</strong> Self-hosted LLM makes per-SKU
              generation cost negligible; direct API integrations eliminate the manual agency middleman;
              credit model aligns pricing with customer value
            </p>
          </div>
        </section>

        {/* Product specification */}
        <section>
          <h2 className="text-2xl font-bold text-white">Product specification</h2>
          <p className="mt-4 text-gray-300">
            <strong className="text-white">Target customer:</strong> Manufacturers, distributors, and wholesale
            sellers needing to list 100–10,000 SKUs across multiple marketplaces — currently paying listing
            agencies per SKU
          </p>

          <h3 className="mt-8 text-lg font-semibold text-white">Core MVP features</h3>
          <ul className="mt-4 space-y-2">
            {coreFeatures.map((f) => (
              <li key={f.slice(0, 40)} className="flex gap-3 text-gray-300">
                <span className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-brand-400" />
                {f}
              </li>
            ))}
          </ul>

          <div className="mt-8 space-y-4 text-gray-300">
            <p>
              <strong className="text-white">Pricing:</strong> Credit-based (per SKU published) with monthly
              subscription floor at $99/month base (includes 500 SKU publishes); $0.15 per additional SKU —
              vs listing agencies charging $1–3 per SKU per marketplace
            </p>
            <p>
              <strong className="text-white">Go-to-market:</strong> r/IndiaBusiness, r/FulfillmentByAmazon,
              LinkedIn outreach to export manufacturers, Indiamart seller communities, Amazon seller Facebook groups
            </p>
            <p>
              <strong className="text-white">Competitive landscape:</strong> Listing Mirror and Codisto handle
              sync but not AI generation from raw specs. No tool specifically targets manufacturers going from
              raw product data → published listings at scale.
            </p>
            <p>
              <strong className="text-white">Agentic automation plan:</strong> Ingestion agent parses uploaded
              spreadsheets and normalizes data; generation agent creates all listing content via LLM; QA agent
              scores and flags issues; publish agent batches API calls to marketplaces; error agent retries failed
              publishes and notifies user — human only reviews flagged low-quality listings before final publish
            </p>
            <p>
              <strong className="text-white">MVP estimate:</strong> Python + LLaMA 3 via Ollama + Amazon SP-API
              + eBay API + Shopify API + Postgres + React upload/review UI; 4 weeks solo dev
            </p>
          </div>
        </section>

        {/* Validation checklist */}
        <section>
          <h2 className="text-2xl font-bold text-white">Validation checklist (9/9)</h2>
          <div className="mt-6 grid gap-3 sm:grid-cols-2">
            {checklistItems.map((item) => (
              <div
                key={item.label}
                className="flex items-center gap-3 rounded-xl border border-emerald-500/20 bg-emerald-500/5 px-4 py-3"
              >
                <span className="flex h-6 w-6 items-center justify-center rounded-full bg-emerald-500/20 text-sm text-emerald-400">
                  ✓
                </span>
                <span className="text-sm text-gray-300">{item.label}</span>
              </div>
            ))}
          </div>
        </section>

        {/* Source pain points */}
        <section>
          <h2 className="text-2xl font-bold text-white">Source pain points (real posts)</h2>
          <div className="mt-6 space-y-6">
            {painPoints.map((pp) => (
              <div key={pp.url} className="glass-card p-6">
                <p className="leading-relaxed text-gray-200">{pp.problem}</p>
                <dl className="mt-4 grid gap-2 text-sm sm:grid-cols-2">
                  <div>
                    <dt className="text-gray-500">Persona</dt>
                    <dd className="text-gray-300">{pp.persona}</dd>
                  </div>
                  <div>
                    <dt className="text-gray-500">Workaround</dt>
                    <dd className="text-gray-300">{pp.workaround}</dd>
                  </div>
                  <div>
                    <dt className="text-gray-500">Frequency</dt>
                    <dd className="text-gray-300">{pp.frequency}</dd>
                  </div>
                  <div>
                    <dt className="text-gray-500">WTP signal</dt>
                    <dd className="text-gray-300">{pp.wtp}</dd>
                  </div>
                </dl>
                <a
                  href={pp.url}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="mt-4 inline-flex items-center gap-1 text-sm text-brand-400 transition hover:text-brand-300"
                >
                  View source post →
                </a>
              </div>
            ))}
          </div>
        </section>

        {/* Footer note */}
        <section className="border-t border-white/10 pt-8 text-center text-sm text-gray-500">
          <p>Generated by Idea Miner run 2026-07-10-pm on 2026-07-10 19:20 UTC</p>
          <Link href="/demo" className="mt-4 inline-block text-brand-400 transition hover:text-brand-300">
            Try the interactive demo →
          </Link>
        </section>
      </article>
    </div>
  );
}
